name: .NET CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Specify the version of .NET

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: dotnet restore code/ExpenseManger-Backend.sln

      # Step 4: Build the project
      - name: Build
        run: dotnet build code/ExpenseManger-Backend.sln --no-restore --configuration Release

      # Step 5: Run Tests
      - name: Run Tests
        run: dotnet test code/tests --no-build --verbosity normal
