name: .NET CI Workflow with Release Mode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Restore Dependencies
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore code/ExpenseManger-Backend.sln

  lint:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
  
      - name: Check Code Formatting
        run: dotnet format --verify-no-changes

  # Build the Solution in Release Mode
  build:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build Solution in Release Mode
        run: dotnet build code/ExpenseManger-Backend.sln --configuration Release --output ./output

  # Run Unit Tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Tests
        run: dotnet test code/ExpenseManger-Backend.sln --configuration Release --verbosity normal

  # Upload Build Artifacts
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./output/*
