name: CI/CD Deployment of .NET 8 API to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - Development

# ✅ Parallel Build and Setup Jobs
jobs:
  # ✅ Build Job
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish the API
      run: |
        cd code/src/FinanceManager.API
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    - name: Store build artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-publish
        path: code/src/FinanceManager.API/publish

  # ✅ Setup Job (Runs in Parallel with Build)
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build
    
    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Store SSH configuration
      uses: actions/upload-artifact@v4
      with:
        name: ssh-config
        path: ~/.ssh

---

  # ✅ Deploy Job (Waits for Both Build and Setup to Finish)
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [build, setup]  # ⚠️ Ensure deploy waits for both jobs

    steps:
    - name: Download SSH config
      uses: actions/download-artifact@v4
      with:
        name: ssh-config
        path: ~/.ssh

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: api-publish
        path: ./publish

    - name: Set SSH permissions
      run: |
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh

    - name: Copy build artifacts to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/ec2-expense-manager-api

    - name: Deploy and restart service on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl stop kestrel-api || true
          sudo mkdir -p /var/www/ec2-expense-manager-api
          sudo chown -R ec2-user:ec2-user /var/www/ec2-expense-manager-api
          sudo chmod -R 755 /var/www/ec2-expense-manager-api
          sudo systemctl start kestrel-api
          sudo systemctl status kestrel-api
