name: CI/CD Deployment of .NET 8 API to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - Development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    # ✅ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # ✅ Build and publish
    - name: Build and publish the API
      run: |
        cd code/src/FinanceManager.API
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    # ✅ Compress the publish folder
    - name: Compress publish folder for transfer
      run: |
        tar -czf api-publish.tar.gz -C code/src/FinanceManager.API/publish .

    # ✅ Deploy to EC2
    - name: Deploy to EC2 with environment secrets
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # ✅ Stop the existing service (if running)
          sudo systemctl stop kestrel-api || true

          # ✅ Ensure the target directory exists
          sudo mkdir -p /var/www/ec2-expense-manager-api
          sudo chown -R ${{ secrets.EC2_USER }}:$USER /var/www/ec2-expense-manager-api
          sudo chmod -R 755 /var/www/ec2-expense-manager-api

          # ✅ Upload the compressed build to EC2
          scp -o StrictHostKeyChecking=no api-publish.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/ec2-expense-manager-api

          # ✅ Extract the build
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/ec2-expense-manager-api
            tar -xzf api-publish.tar.gz
            rm -f api-publish.tar.gz
          EOF

          # ✅ Restart the service
          sudo systemctl start kestrel-api
          sudo systemctl status kestrel-api
