name: CI/CD Deployment of .NET 8 API to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - Development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    # ✅ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # ✅ Build and publish
    - name: Build and publish the API
      run: |
        cd code/src/FinanceManager.API
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./publish

    # ✅ Deploy to EC2
    - name: Deploy to EC2 with environment secrets
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # ✅ Add host key to avoid verification issues
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # ✅ Stop the existing service
          sudo systemctl stop kestrel-api || true

          # ✅ Ensure the directory exists with proper permissions
          sudo mkdir -p /var/www/ec2-expense-manager-api
          sudo chown -R ${{ secrets.EC2_USER }}:$USER /var/www/ec2-expense-manager-api
          sudo chmod -R 755 /var/www/ec2-expense-manager-api

          # ✅ Deploy the new version
          scp -r ./code/src/app/publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/ec2-expense-manager-api

          # ✅ Restart the service
          sudo systemctl start kestrel-api
          sudo systemctl status kestrel-api
